### PR TITLE
fix dark mode bugs with border-width and ProfileCalendar

### LINKED ISSUE #24: Bugs in dark theme
Currently the dark theme has a few minor bugs:

- When switching to dark theme, some elements appear to slightly move/change size
- The Contribution Graph displays 0 contributions in white instead of gray like github

I wish to fix them, please tag this issue and assign it to me.

### PR DESCRIPTION
**Pull request by xnatsuk**
Closes #24

### CODE REVIEW

**Comment by Mridul2820** [comment]
Hi @xnatsuk, borders are required. Without the borders, the cards are separate from each other.

**Comment by xnatsuk** [comment]
Seemed okay to me. I'll add them again

**Comment by xnatsuk** [comment]
@Mridul2820 borders should be the same size across both themes now.

**Comment by Mridul2820** [comment]
Hi @xnatsuk, a few things if you enhance for the dark mode, it will look great

- [x] user card URL color
- [x] User stats captions color
- [x] User followers name color
- [x] Most Forked, Most Stared, Contribution Graph axis label color

**Comment by xnatsuk** [comment]
@Mridul2820 I didn't fix the axis label color because I'm not familiar with it's dependency, but the other colors are more visible now.

**Review by Mridul2820 — APPROVED** [review]

**Comment by Mridul2820** [comment]
Thank you for contributing! 🚀

**Pull request merged**
