### PR TITLE
feat(ProfilePinnedRepositories): adds a card with pinned repositories from the user

### LINKED ISSUE #14: Show Pinned Repository of the User
Show the pinned repository of the user in a card

### PR DESCRIPTION
**Pull request by christianfds**
Closes #14

### CODE REVIEW

**Comment by Mridul2820** [comment]
Hi @christianfds You have done great work.
Just a few changes needed 

- [ ] Can you make the fork star icons the same on GitHub
- [ ] Can you add a repo symbol in front of the repo name
- [ ] And add a language color circle like GitHub at the bottom of every card

**Comment by christianfds** [comment]
@Mridul2820 just did all the requested changes and also merged with main and added the dark theme to the component.

~I'm just having an small bug with this div:~

image

~For some reason it only loads the classes if i add/remove something and the element hot reloads on screen, but when i hit F5 there are no classes again '-'~

image


~Do you have any ideia why this might be happening?~

NVM, its working now

**Comment by Mridul2820** [comment]
There is a wired bug for pinned repo cards. The overflow scroll is gone
Screenshot from 2022-10-13 09-33-54
Can you please look at that?

**Comment by christianfds** [comment]
Yeah, that's exactly what has happening when i was testing. After i cleaned every tmp, cache, cookie i could think and it worked I thought it was something in here. I will take another look at it, maybe rewrite somethings.

**Pull request merged**
